name: Build the book, test the examples

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_book:
    name: Build book
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.5'

      - run: mdbook build

  test_examples:
    name: Test example code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - uses: actions-rs/cargo@v1
        with:
          command: test
